### ISSUE TITLE
Is this comment incorrect?

### ISSUE THREAD

**Issue by discapes** [zelbrium/gllabel#20]
I'm trying to understand how the library works, thanks a lot for making comments.
So what I have gathered, each grid cell is 1 pixel, which is 4 bytes. The index of a bezier is represented by one byte, so per grid cell, there can be 4 beziers. As said in this comment in vgrid.hpp:
>	Bytes per pixel, aka. how many bezier curves are allowed per grid
	cell. This should probably always be 4, since that's the limit of
	bytes per pixel that OpenGL supports (GL_RGBA8).
	`uint8_t depth;`

Then in vgrid.cpp there's this comment:
>  Each grid cell is represented as one byte in the atlas, and values 0 and 1
 are reserved for special meaning. This leaves a limit of 254 beziers per
 grid/glyph.

Shouldn't that be "Each bezier index is represented as one byte in the grid cell, ...", because each grid cell is represented as 1 pixel?

**Comment by azsn** [comment]
Yep, you're right, it should say "Each bezier index is" not "Each grid cell is". If you want to make a PR for that, go ahead. I'd appreciate if you ensure the edited comment lines stay under 80 columns. (EDIT: Also note that a number of places I've written "pixel" I mean "texel", what OpenGL calls a texture pixel. I'll fix those where appropriate.)

If you're trying to understand how this library works, definitely read
https://wdobbie.com/post/gpu-text-rendering-with-vector-textures/
and
https://wdobbie.com/post/gpu-text-rendering-with-vector-textures-details/
if you haven't already. It outlines how the algorithm works. Will made a demo using a [pregenerated bezier and grid atlas](https://wdobbie.com/pdf/atlas.bmp) via "a C++ program", but he did not share that program as far as I know. Most of the logic in this library is simply implementing the code necessary to generate these bezier and grid atlases on the fly instead of requiring them to be pregenerated. (Note that the way he stores the data in the atlas is a bit different from how I do it, and he combines the bezier and grid atlases into one texture, which is why his atlas looks different.)

**Comment by azsn** [comment]
Also keep in mind if you're reading through stuff in `gllabel.cpp`, I'm still working through cleaning up all the garbage and near-unusable code I left behind in that file 4 years ago :) The code I've extracted and reworked into the other files in `lib/` is (hopefully) more understandable.

**Comment by discapes** [comment]
> The code I've extracted and reworked into the other files in lib/ is (hopefully) more understandable.

Yes, definitely. I've looked at Will's articles before, I'm sure the implementation notes at least become increasingly useful when I'm looking into this. 
One thing I'm also wondering about is that is the singleton-on-heap pattern any good? I'd just use variables inside a private namespace or something. And it seems like all the atlas data is uploaded to the GPU on each frame. I'd maybe have a separate GLLFace class that contains the FT_Face and the atlases

**Comment by azsn** [comment]
I'm not sure what you mean by "singleton-on-heap pattern", which thing are you referring to?

The atlas data is not uploaded every frame -- notice the atlas has an `uploaded` variable that gets marked true when it's been uploaded and it's [checked in `UploadAtlases`](https://github.com/zelbrium/gllabel/blob/871337499d93090aa451607b5b688bd25ececef8/lib/gllabel.cpp#L668) so it doesn't upload the atlas again. The `uploaded` var is set false again when it changes.

That said, there are plenty of problems with the whole atlas algorithm right now. For example, I have some code to handle multiple atlases (e.g. if the 1st atlas fills up) but it's not fully implemented and so doesn't work. Another problem is it always reuploads the entire atlas, not just what changes. My current work on this project is fixing these problems.

**Comment by discapes** [comment]
I see. I meant that there is a singleton GLFontManager that is allocated on the heap.

**Comment by azsn** [comment]
Oh yes. My end-plan for that is to allow users of `GLLabel` to use a particular instance of a font manager or to use the default singleton. The reason being that in most cases, it's better to share one font manager across many labels because it reduces duplicate atlas data in GPU memory if all the labels use the same glyphs (e.g. a-z, A-Z, 0-9). However, if different sets of labels are using completely disjoint sets of glyphs (say, separate russian and hebrew labels), it might be more efficient to render them with separate sets of atlases. So the user could define separate font managers for the different categories of labels. I'm probably overthinking all of this, but whatever, I'm having fun with it :-)

As for heap, there's not any problem with allocating a singleton on the heap.

**Comment by azsn** [comment]
Issue fixed in #21
