### ISSUE TITLE
Vector subscript out of range

### ISSUE THREAD

**Issue by discapes** [zelbrium/gllabel#4]
I'm getting a `Debug assertion failed: vector subscript out of range`.
For some reason I can't find out where it is coming from.
I made a self-contained fork of your project, with the following changes
- GLEW to GLAD
- Make to CMake (a lot better, do `cd build`, `cmake ..` and `cmake --build .`
- I disabled the forward compatibility window hint so the shader code would work
- Using my own fonts, my loadTTF() renders them to the terminal to make sure that my code isnt at fault
- added 2 casts to double so it would compile

https://github.com/discapes/gllabel

Also it said something about "MORE THAN 4 on 112"

**Comment by azsn** [comment]
Cool fork! I'm not sure cmake is necessary for such a small demo project, but sure. I'm very not up-to-date on modern OpenGL practices, is there a benefit to GLAD over GLEW?

I'll see if I can get this project building and working tonight or tomorrow and figure out this `out of range` bug. Enough excuses, I should finish this thing..... keep in mind this is just a demo project, making this into a real library would be too much for me :(

**Comment by discapes** [comment]
Yeah I've seen on the interwebz that GLAD is better than GLEW. Also thanks for replying so fast. I did some more investigation and found specifically where the bug happens (at the green arrow):
![image](https://user-images.githubusercontent.com/48839377/94565325-bb305900-0271-11eb-954f-d005bb9a0c6b.png)
demo.cpp line 157 is `fpsLabel.SetText(toUTF32(stream.str()), 1, glm::vec4(0,0,0,1), defaultFace);´ btw
So it tries access verts[0], but verts is size 0

**Comment by azsn** [comment]
I'm pretty sure I see the bug. I'm guessing it didn't happen to me but is happening to you is because you're using a different C++ library than me (looks like you're on Windows VC++ vs I was using g++), and those will have different undefined behaviors. In this case, it looks like me indexing 0 of an empty array didn't crash but for you it does (which it should).

It looks like when `RemoveText` is called with `(0, this->text.size())`, as it is in this case, `this->verts` is rightfully completely emptied. Then, at the end of `RemoveText`, it uploads the new data to the buffer via `glBufferSubData`. But in the case of an empty `this->verts`, it should just erase all data in the buffer. Probably something like this:

```
glBindBuffer(GL_ARRAY_BUFFER, this->vertBuffer);

if (this->verts.size() > 0) {
	glBufferSubData(GL_ARRAY_BUFFER,
		index*6*sizeof(GlyphVertex),
		(this->verts.size() - index*6)*sizeof(GlyphVertex),
		&this->verts[index*6]);
} else {
	glBufferData(GL_ARRAY_BUFFER, 0, NULL, GL_DYNAMIC_DRAW);
}
```

Although this resets the buffer's capacity to 0, which may be inefficient. From `InsertText`, it looks like I'm reusing `std::vector`'s "capacity" functionality to determine how big to preallocate the GL buffer, so that I don't have to figure out a good algorithm on my own lol. So maybe a better erase call would be

```
glBufferData(GL_ARRAY_BUFFER, this->verts.capacity() * sizeof(GlyphVertex), NULL, GL_DYNAMIC_DRAW);
```

Which will keep the buffer with a little bit of room to prepare for future verts. .... or, given that I think the contents/size of the vertex buffer does not determine how many verts actually get rendered (that's determined in the `Render` function I believe), the `else` clause of the `if/else` above could probably just do nothing -- make no change to the contents of the verts buffer, leaving behind whatever was there to get overwritten by the next `InsertText`.

... all assuming that's actually the bug :) I'm just looking at the code, haven't ran anything yet.

**Comment by discapes** [comment]
That seems to fix it. Although I still just see a blank background. Ill look at it in renderdoc right now.... When I get it fully working I'll check out if the else clause can be removed
![image](https://user-images.githubusercontent.com/48839377/94574070-6396eb00-027b-11eb-9e59-b14eb3a68c05.png)

**Comment by azsn** [comment]
Hey, I think I found the bugs. I just pushed a commit which cleans up some stuff, and I got it fully working on my Mac. You can see the commit message for details, but I think ultimately the bugs were me initializing the `uTransform` shader variable incorrectly and initializing the `glm::mat4` identity matrices incorrectly (which I now see was already mentioned in #1 -- would have saved me some debugging time if I had remembered to look at that, lol).

I haven't pulled in (or really looked at in detail) your changes though, sorry about that -- I wanted to try to fix the bugs while changing as little as possible for now. Let me know if the demo works for you now with my new commit.

Also I realized I never responded to `Also it said something about "MORE THAN 4 on 112"` in your original post. I believe that happens when more than 4 bezier curves in a glyph intersect one grid cell. Basically, it means the glyph is too dense with detail for this algorithm (as currently implemented) to handle, and so that character might render slightly corrupted. The easy fix is to just to make the grid atlas have a higher resolution, but that wastes space for all the glyphs that don't need it. I'm not really sure how to best handle that problem.

**Comment by discapes** [comment]
> I haven't pulled in (or really looked at in detail) your changes though, sorry about that

Yeah my changes were kinda bad because they switched the build system, something which definitely wasn't needed. But I decided I want to participate in Hacktoberfest by helping with this repo, so I undid the original bad changes, prepared some fixes to the font lookup yesterday by checking an alternative path (on my Arch), but it seems like you came up with a better solution just now. Well, I PRed to the fork's master anyway, but now I'll go merge upstream somehow and see if there's something else I can contribute... close?

**Comment by azsn** [comment]
Ah, sorry, yeah I thought it would make things easier to just put some fonts in the repo.

My plan for this project was to actually make the GLLabel class able to render arbitrary text well, just like any textbox in any regular GUI library. That means using a text-handling library like Pango so that the user of GLLabel can pass in any Unicode string, a width, height, justification rules, fonts, etc. and have it be layed-out appropriately. Then my code can render it, and I (hopefully) don't have to worry about the ridiculous complexities of text layout :)

But to do that I need to clean up everything. Throw out all the bad layout stuff I wrote initially and extract the basic rendering functionality, probably into one or more separate classes. (e.g. maybe one class that does the atlas generation with no GL dependencies, another that does the GL rendering, and finally the original GLLabel which combines the two and uses Pango for layout).

If you're interested in helping with any of that, let me know!
