### ISSUE TITLE
Whats the -framework option supposed to mean?

### ISSUE THREAD

**Issue by discapes** [zelbrium/gllabel#5]
![image](https://user-images.githubusercontent.com/48839377/94968074-ee404a00-0508-11eb-8230-3d6c99203268.png)

**Comment by discapes** [comment]
for me I had to replace it with -lGL, maybe we should make that the default?

**Comment by azsn** [comment]
Frameworks are a Mac thing. They're effectively like shared libraries but instead of passing `-l` to the linker, you pass `-framework`. Every platform and environment is going to have different libraries to link and header paths to include, so I'm just going to leave it as is, at least for now. Unless there's a good way to automatically support every platform lol. `pkg-config` doesn't always work so well.

(It looks like you might be on Mac from the screenshot, if that's the case the unrecognized option might be because you're using real g++ instead of the Mac g++ which is actually just Clang.)
